#! /usr/bin/env bash

if [ $# -eq 0 ]; then
    args="-v ArduCopter --frame gazebo-artemis --model JSON --console --map -L UdeS"
else
    args="-v ArduCopter --frame gazebo-artemis --model JSON $@"
fi

exec $ARTEMIS_SIM_VEHICLE_PATH/sim_vehicle.py $args
